---
title: "Evolutionary Dynamics Homework 6"
date:  "`r format(Sys.time(), '%B %d, %Y %H:%m')` (`r Sys.timezone()`)"
author: "Minghang Li"
mainfont: "KpRoman"
output:
  pdf_document:
    latex_engine: xelatex
    extra_dependencies:  [ "amsmath", "amsthm", "amssymb", "cancel", "unicode-math", "csquotes" ]
---

# Problem 1: One-dimensional Fokker-Planck equation

\begin{displayquote}
Consider the one-dimensional Fokker-Planck equation with constant coefficients,


\begin{equation}
\label{eq:one-dim-fokker-planck}
\partial_t \psi(p,t) = −m \partial_p \psi(p,t)
+ \frac{v}{2} \partial_p^2 \psi(p,t),
\end{equation}

with $p \in \mathbb{R}, v > 0$.
\end{displayquote} 

## (a) See below.

\begin{displayquote}
Show that for vanishing selection, $m = 0$,
 
\begin{equation}
\label{eq:solution}
\psi (p,t) = 
  \frac{1}{\sqrt{2 \pi vt}} 
  \exp\left(− \frac{p^2}{2vt} \right)
\end{equation}

solves the Fokker-Planck equation. To which initial condition does this solution correspond?
 \end{displayquote}

---

For vanishing selection $m = 0$, the Fokker-Planck equation can be written as simply

\begin{equation}
\label{eq:vanishing-selection}
\partial_t \psi(p, t) = \frac{v}{2} \partial_p^2 \psi(p, t)
\end{equation}

Let's compute the left-hand side and the right-hand side to show that the solution is correct.

### LHS of \eqref{eq:vanishing-selection}

\begin{equation}
\label{eq:LHS}
\begin{aligned}
\partial_t \psi(p, t) &= \partial_t \left( \frac{1}{\sqrt{2 \pi vt}} \exp\left(− \frac{p^2}{2vt} \right) \right) \\
&= - \frac{1}{\sqrt{2 \pi vt} \cdot 2t} \cdot \exp \left(-\frac{p^2}{2vt} \right) 
+ \frac{1}{\sqrt{2 \pi vt}} \cdot \frac{p^2}{2vt^2} \cdot \exp \left(-\frac{p^2}{2vt} \right) \\
&= \frac{p^2 - vt}{2vt^2} \cdot 
  \frac{1}{\sqrt{2 \pi vt}} \cdot 
  \exp \left( -\frac{p^2}{2vt}\right)
\end{aligned}
\end{equation}

### RHS of \eqref{eq:vanishing-selection}

\begin{equation}
\label{eq:RHS}
\begin{aligned}
\frac{v}{2} \partial_p^2 \psi(p, t) 
&= \frac{v}{2}\partial_p \left(
  \partial_p \left( 
    \frac{1}{\sqrt{2 \pi vt}} \exp\left(− \frac{p^2}{2vt} \right) 
  \right) 
\right) \\
&= \frac{v}{2 \sqrt{2 \pi vt}} \partial_p \left(
  \partial_p \left( \exp\left(− \frac{p^2}{2vt} \right) \right) 
\right) \\
&= \frac{v}{2 \sqrt{2 \pi vt}} \partial_p \left(
  \left( -\frac{p}{vt} \right) \cdot \exp\left(− \frac{p^2}{2vt} \right)
\right) \\
&= \frac{v}{2 \sqrt{2 \pi vt}} \cdot \left(
  -\frac{1}{vt} \exp\left(− \frac{p^2}{2vt} \right) +
  \frac{p^2}{v^2t^2} \cdot \exp\left(− \frac{p^2}{2vt} \right)
\right) \\
&= - \frac{1}{\sqrt{2 \pi vt} \cdot 2t} \cdot \exp \left(-\frac{p^2}{2vt} \right) 
+ \frac{1}{\sqrt{2 \pi vt}} \cdot \frac{p^2}{2vt^2} \cdot \exp \left(-\frac{p^2}{2vt} \right) \\
&= \frac{p^2 - vt}{2vt^2} \cdot 
  \frac{1}{\sqrt{2 \pi vt}} \cdot 
  \exp \left( -\frac{p^2}{2vt}\right)
\end{aligned}
\end{equation}

It's clear that \eqref{eq:LHS} equals \eqref{eq:RHS}, so \eqref{eq:solution} is indeed the solution.

To investigate the initial condition, we need to examine the behavior of $\psi (p, t)$ as $t \to 0^+$. As $t \to 0^+$, we have:

- The exponential term $\exp(-p^2 / (2vt))$ approaches:
  - $0, \forall p \neq 0$ becuase $-p^2 / (2vt) \to -\infty$
  - $1$ for $p = 0$.
- The prefactor $\frac{1}{\sqrt{2 \pi vt}}$ approaches $\infty$ for $t \to 0^+$.

This behavior is consistent with the Dirac delta function $\delta(p)$. Hence, the initial condition is 

$$
\psi (p, 0) = \delta(p),
$$
where $\delta(p)$ is the Dirac delta function defined as

$$
\delta(p) = \left\{\begin{aligned}
&0, && \text{if } p \neq 0, \\
&\infty, && \text{if } p = 0.
\end{aligned}
\right.
$$

This means the initial distribution is concentrated at $p = 0$, which represents the fact that the starting population is initially at a single allele frequency.

## (b) Construct a solution for constant selection, $m \neq 0$, by substituting $z = p − mt$ for $p$ in \eqref{eq:one-dim-fokker-planck} . What is the mean and variance?

Let $z(p, t) = p - mt$, then we have $\partial_p z(p, t) = 1$, and $\partial_t z(p, t) = -m$. Substitute $z(p,t)$ into $\psi (p,t)$ to obtain $\psi(z, t)$, using the chain rule, we have

\begin{equation}
\label{eq:psi_partial_t}
\begin{aligned}
\frac{\partial \psi(p, t)}{\partial t} &=
  \frac{\partial \psi(z, t)}{\partial z} \frac{\partial z}{\partial t} + \frac{\partial \psi(z, t)}{\partial t} \frac{\cancel{\partial t}}{\cancel{\partial t}} \\
  &= -m \frac{\partial \psi(z, t)}{\partial z} + \frac{\partial \psi(z, t)}{\partial t} \\
\end{aligned}
\end{equation}

\begin{equation}
\label{eq:psi_partial_p}
\begin{aligned}
\frac{\partial \psi(p, t)}{\partial p} &=
  \frac{\partial \psi(z, t)}{\partial z} \frac{\partial z}{\partial p} \\
  &= \frac{\partial \psi(z, t)}{\partial z}
\end{aligned}
\end{equation}

Using \eqref{eq:psi_partial_t} and \eqref{eq:psi_partial_p}, we can rewrite the Fokker-Planck equation:

\begin{equation}
\label{eq:similar_to_3}
\begin{aligned}
\frac{\partial \psi (p, t)}{\partial t} &= -m \frac{\partial \psi (p, t)}{\partial p} + \frac{v}{2} \frac{\partial^2 \psi (p, t)}{\partial p^2} \\
\cancel{-m \frac{\partial \psi (z, t)}{\partial z}} + 
\frac{\partial \psi (z, t)}{\partial t} 
  &= \cancel{-m \frac{\partial \psi (z, t)}{\partial z}}
   + \frac{v}{2} \frac{\partial^2 \psi (z, t)}{\partial z^2} \\
\frac{\partial \psi (z, t)}{\partial t} &= 
  \frac{v}{2} \frac{\partial^2 \psi (z, t)}{\partial z^2}
\end{aligned}
\end{equation}

Voila! This equation \eqref{eq:similar_to_3} has exactly the same form as \eqref{eq:vanishing-selection}, so the solution is of the form of \eqref{eq:solution} also. We use the same form and subsitute $z = p - mt$ into it:

$$
\begin{aligned}
\psi(z, t) &= \frac{1}{\sqrt{2 \pi vt}} \exp\left(− \frac{z^2}{2vt} \right) \\
\psi(p, t) &= \frac{1}{\sqrt{2 \pi vt}} \exp\left(− \frac{(p - mt)^2}{2vt} \right) \sim \mathcal{N}(mt, vt)
\end{aligned}
$$

Hence, the mean is $mt$ and the variance is $vt$.

# Problem 2: Diffusion approximation of the Moran process

\begin{displayquote}
Derive a diffusion approximation for the Moran process of two species. Assume the first species has a small selective advantages.
\end{displayquote}

## (a) See below.

\begin{displayquote}
The general definition for the drift coefficient is

\begin{equation}
\label{eq:drift_coeff}
M(p)=E[X(t)−X(t−1)|X(t−1)=i]/N,
\end{equation}

where $p=i/N$ and $X(t)$ denotes the abundance of the first allele. Evaluate this expression for the Moran process with selection. Show that this yields the result for the Wright-Fisher process from the lecture, divided by $N$.
\end{displayquote}

---

From lecture 3 we know that for a _neutral_ Moran process we have transition probabilities:

- $P_{i,i+1} = p(1-p)$
- $P_{i, i-1} = (1-p)p$
- $P_{i,i} = p^2 + (1-p)^2$

However, since the first species has a small selective advantage (denoted as $s$ hereafter), we need to modify the transition probabilities. We have:

- $P_{i,i+1} = (p(1 + s)/(p(1 + s) + (1-p))) \cdot (1-p) = (p(1+s) / (1 + sp)) \cdot (1-p)$
- $P_{i, i-1} = (1-p)/(1 + sp) \cdot p$
- $P_{i,i} = 1 - P_{i,i+1} - P_{i,i-1}$

And the expectation derived from the transition probabilities is:

\begin{equation}
\label{eq:expectation}
\begin{aligned}
E[X(t)|X(t-1) = i] 
  &= i \cdot P_{i,i} + (i+1) \cdot P_{i,i+1} + (i-1) \cdot P_{i,i-1} \\
  &= i \cdot (1 - P_{i,i+1} - P_{i,i-1}) + (i+1) \cdot P_{i,i+1} + (i-1) \cdot P_{i,i-1} \\
  &= i + P_{i,i+1} - P_{i,i-1} \\
  &= i + \frac{p(1+s)}{1+sp} \cdot (1-p) - \frac{1-p}{1 + sp} \cdot p \\
  &= i + \frac{sp(1-p)}{1+sp}
\end{aligned}
\end{equation}

Using \eqref{eq:expectation} and \eqref{eq:drift_coeff}, we can calculate the drift coefficient $M(p)$:

\begin{equation}
\label{eq:drift_coefficient_simplified}
\begin{aligned}
M(p) &= \frac{E[X(t)−X(t−1)|X(t−1)=i]}{N} \\
&= \frac{E[X(t)|X(t−1)=i] - E[X(t−1)|X(t−1)=i]}{N} \\
&= \frac{E[X(t)|X(t-1)=i] - i}{N} \\
&= \left( i + \frac{sp(1-p)}{1+sp} - i \right)/N \\
&= \frac{sp(1-p)}{N(1+sp)}
\end{aligned}
\end{equation}

From slide 33, we know that the drift coefficient for the Wright-Fisher process is:

$$
M_{WF}(p) = \frac{sp(1-p)}{1+sp},
$$

and \eqref{eq:drift_coefficient_simplified} is exactly the result for the Wright-Fisher process divided by $N$.

## (b) By a similar argument calculate the diffusion coefficient $V(p)$.

From slides, we have

\begin{equation}
\label{eq:variance}
\begin{aligned}
V(p) &= E\left[Var[p(t+1)] | p(t)\right] \\
     &= \frac{1}{N^2} E\left[Var[X(t+1)|X(t)]\right]
\end{aligned}
\end{equation}

To derive $Var[X(t+1)|X(t)]$ again, we first derive $Var[X(t+1)|X(t) = i]$:

\begin{equation}
\label{eq:variance_given_i}
\begin{aligned}
Var[X(t+1) | X(t) = i] 
  &= Var[X(t)] + Var[X(t+1) - X(t) | X(t) = i] \\
  &= 0 + E[(X(t+1) - X(t))^2 | X(t) = i] - E[X(t+1) - X(t)| X(t) = i]^2 \\
  &= (i-1-i)^2 \cdot P_{i,i-1} + (i+1-i)^2 \cdot P_{i,i+1} + (i-i)^2 \cdot P_{i,i} 
     - E[X(t+1) - X(t) | X(t) = i]^2 \\
  &= P_{i,i-1} + P_{i,i+1} - E[X(t+1) | X(t) = i]^2 \\
  &= \frac{p(1-p)}{1+sp} + \frac{(1+s)p(1-p)}{1+sp} - \left(\frac{sp(1-p)}{1+sp}\right)^2 \\
  &= \frac{p(1-p)(s + 2)}{1+sp} - \left(\frac{sp(1-p)}{1+sp}\right)^2 \\
  &= p(1-p) \left( 1 + \frac{1+s}{(1+sp)^2} \right)
\end{aligned}
\end{equation}

As \eqref{eq:variance_given_i} is not related to $i$ at all, we can say that the expression of $Var[X(t+1)|X(t)]$ is the same as \eqref{eq:variance_given_i}. Plug \eqref{eq:variance_given_i} back to \eqref{eq:variance}, we obtain the diffusion coefficient:

\begin{equation}
\label{eq:diffusion_coefficient}
V(p) = \frac{1}{N^2} \left(
  p(1-p) \left( 1 + \frac{1+s}{(1+sp)^2} \right)
\right)
\end{equation}


## (c) Use your results from (a) and(b) in the forward Kolmogorov equation to present a diffusion equation for the Moran model.

Plug in \eqref{eq:drift_coefficient_simplified} and \eqref{eq:diffusion_coefficient} into the forward Kolmogorov equation:

$$
\begin{aligned}
\frac{\partial \psi(p, t)}{\partial t}
  &= - \frac{\partial}{\partial p} \left[
      \psi (p, t) M(p)
    \right] +
    \frac{1}{2} \frac{\partial^2}{\partial p^2} \left[
      \psi (p, t) V(p)
    \right] \\
  &= - \frac{\partial}{\partial p} \left[
      \psi (p, t) \frac{sp(1-p)}{N(1+sp)}
    \right] +
    \frac{1}{2} \frac{\partial^2}{\partial p^2} \left[
      \psi (p, t) \frac{1}{N^2}p(1-p)\left(1 + \frac{1+s}{(1+sp)^2}\right)
    \right]
\end{aligned}
$$

## (d) See below.

\begin{displayquote}
Now assume that $s \leq 1$. Approximate your results from (a) and (b) and use the general expression for the fixation probability $\rho(p_0)$ to show that the fixation probability is given by:

\begin{equation}
\label{eq:fixation_probability}
\rho(p_0 = 1/N) = \frac{1-e^{-s}}{1-e^{-Ns}}
\end{equation}
\end{displayquote}

## (e) Take the limit to derive a result for the fixation probability of a neutral allele, $s=0$. Evaluate \eqref{eq:fixation_probability} for $N=10$ and $N=1000$ for both positive and negative selection, $s=2\%$, and $s=-2\%$, respectively. Compare your result with $\rho_1$ of the exact Moran process.


# Problem 3: Absorption time in the diffusion approximation

\begin{displayquote}
In the diffusion approximation of a process with absorbing states $0$ and $1$ the expected fixation time, conditioned on absorption in state $1$,reads:

$$
\tau_1(p_0) = 2(S(1) - S(0)) 
  \left(
    \int_{p_0}^1 \frac{\rho(p)(1-\rho(p))}{e^{-A(p)}V(p)} dp + 
    \frac{1 - \rho(p_0)}{\rho(p_0)} \int_{0}^{p_0} \frac{\rho(p)^2}{e^{-A(p)}V(p)} dp
  \right)
$$

 where $\rho(p)$ denotes the fixation probability, 
 $$
 A(p)= \int_0^p \frac{2M(p)}{V(p)}d p, \quad \text{and} \quad S(p) = \exp(-A(p)) dp.
 $$
\end{displayquote}

## (a) Calculate the _conditional expected waiting time for fixation_, $\tau_1(p_0)$, of an allele of frequency $p_0$ in the neutral Wright-Fisher process. Approximate the result for small $p_0$.
 
## (b) Compute $\tau_0$, the conditional expected waiting time until _extinction_ (absorption in state $0$) in the neutral Wright-Fisher process. Also derive the unconditioned expected waiting time $\bar{\tau}$ until either fixation or extinction.
